name: "CD pride"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull emedej/pride-actions:latest

      - name: Stop Docker container
        run: docker stop pride-actions || true

      - name: Remove Docker container
        run: docker rm pride-actions || true

      - name: Run Docker container
        run: docker run --name pride-actions -d -p 8080:8080 emedej/pride-actions:latest